Qiskit/qiskit-js

CHANGELOG.md

The link in the [0.2.0] version does not appear in the current changelog. This PR fixes that, as it includes the link at the end of the file comparing the version 0.1.9 and 0.2.0

Fix the link in version 0.2.0 of the changelog

---

packages/qiskit-sim/README.md

Currently this link results in a 404. This commit updates it to point to
Qiskit/openqasm which was my best guess for this link.

Update OpenQASM link in qiskit-sim README

---

CHANGELOG.md
packages/qiskit-sim/README.md
packages/qiskit-sim/index.js
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/lib/gates.js
packages/qiskit-sim/test/functional/Circuit.js
packages/qiskit-sim/test/functional/gates.js
packages/qiskit-sim/test/functional/index.js

This commit introduces a Gate class to enable passing in instances of
these types when adding gates to a circuit as an alternative to passing
in the name of the gate as a string. 
Having the ability to take a Gate allows for some useful tab completion for new users like myself. The example below show how adding a gate to a circuit can be done:
```console
$ node
> const q = require('./index.js')
> const circuit = new q.Circuit(1)
> circuit.addGate(q.Gate.
q.Gate.__defineGetter__      q.Gate.__defineSetter__      q.Gate.__lookupGetter__      q.Gate.__lookupSetter__      q.Gate.__proto__
q.Gate.hasOwnProperty        q.Gate.isPrototypeOf         q.Gate.propertyIsEnumerable  q.Gate.toLocaleString        q.Gate.valueOf
q.Gate.apply                 q.Gate.arguments             q.Gate.bind …
```

Introduce Gate class

---

CHANGELOG.md
README.md
packages/qiskit-cloud/README.md
packages/qiskit-devs-anu/README.md
packages/qiskit-devs-ibm/README.md
packages/qiskit-devs-js/README.md
packages/qiskit-devs/README.md
packages/qiskit-qasm/README.md
packages/qiskit-sim/README.md
packages/qiskit-utils/README.md

This commit updates the installation instructions for Node.js.
The motivation for this is to be more explicit that v8 is referring to
version 8 of Node.js and not Google V8 engine.

Update Node.js install instruction in README.md

---

CHANGELOG.md
packages/qiskit-devs/README.md

Currently there is one link named `proper packages` that does not have a
values specified for it. There is also another link named `packages` which
points (I'm guessing here) to an IBM internal repository.
This commit suggests updating both links to point to the packages
directory. My reasoning here is that these should point to the currently
supported packages, `qiskit-devs-anu`, `qiskit-devs-ibm`, and
`qiskit-devs-js`.

Update packages links in qiskit-devs

---

CHANGELOG.md
packages/qiskit-sim/lib/gates.js
packages/qiskit-sim/test/functional/gates.js

This commit adds the identity gate.
The motivation for this is that this gate is available in QASM [qelib1.inc](https://github.com/Qiskit/qiskit-js/blob/d7121dedef743cc365a0b8dce2daf732562bc7cc/packages/qiskit-qasm/core/qelib1.inc#L15) but does not exist in the gates currently provided by qiskit-sim.

Add the identity (id) gate

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/test/functional/Circuit.js

This commit returns `this` from addGate to support method chaining.
For example:
```js
const c = new Circuit({ nQubits: 1 });
c.addGate('h', 0, 0).addGate('z', 1, 0).addGate('h', 2, 0).run(10);
```

Support method chaining for addGate

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/test/functional/Circuit.js

This commit adds a factory function named createCircuit that takes the
number of qubits as its sole argument.
The motivation for this is that I've found myself trying to create a new
circuit using new Circuit(3). Having this function allows for just
passing in the number of qubits.

Add createCircuit factory function

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js

Currently initTransform calculates the dimension for the transformation
matrix. This is also done by the methods that call initTranform, init
and createTransform.
This commit suggests adding a parameter initTransform and avoid
calculating this value multiply times.

Add dimension parameter to initTransform

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js

This commit renames the `qbts` variable in Circuit.createTransform to
`unusedWires` in hopes to make it more understandable.
My understanding is that this array represents the unused wires
(indexed in opposite order from the qubits/wires passed into the
createTransform function).
For example, a system of 3 qubits and a single hadamard gate:
```console
qubits                                opposite-order
q[0] ----H--------------------------- q[2]
q[1] -------------------------------- q[1]
q[2] -------------------------------- q[0]
```
In this case qubits/wires used by this gate would be [2] and
qbts/unsuedWires would be [0, 1] (using the opposite-order indexing).

Rename qbts to unusedWires in createTransform

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js

Make amplitudes a member of the Circuit class
Currently numAmplitudes is called by init, createTransform, and
stateToString. While stateToString might not be called, init and
createTransform are both called by run (indirectly by applyGate) and the
value calculated twice.

Make amplitudes a member of the Circuit class

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js

This commit removes the `clear` call from the Circuit constructor and puts
the member initialisation of `gates`, `state`, and `T`, in the constructor
itself.
The motivation for this is to hopefully clarify the state of a
Circuit making it a little easier to follow when one does not have to
follow the `clear()` -> `reset()` -> `resetTransform()` calls to figure this
out.

Remove clear() call from Circuit constructor

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/test/functional/Circuit.js

This commit adds support for executing the same circuit twice (or more
times) in row with the state from the previous execution being used as
the state for the next execution.
The motivation for this came out of wanting to executing a hadamard gate
twice, and while it is possible to add two gates and then run it, having
the ability to run the circuit multiple times gives a nice separation
for someone learning about quantum gates (allows for inspecting/logging
the state if one is not comfortable using a debugger for example).

Allow for executing the same circuit twice

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/test/functional/Circuit.js

I introduces a bug when adding the Gate class which is that when initial
values are passed into the run method the applyGate should be called
with name of the gate and not the Gate instance.
Fixes: https://github.com/Qiskit/qiskit-js/issues/51

Use Gate.x.name for initial values

---

CHANGELOG.md
packages/qiskit-sim/lib/gates.js

Add sphaseShift util function for phase gates
This commit adds a utility function named phaseShift which can be used
by the phase shift gates s, r2, r4, and r8.

Add phaseShift util function for phase gates

---

CHANGELOG.md
packages/qiskit-sim/lib/gates.js

Make r2 gate use the matrix of the s gate
This commit updates the r2 gate to use the unitary matrix of the s gate
instead of redefining it.

Make r2 gate use the matrix of the s gate

---

CHANGELOG.md
packages/qiskit-sim/lib/gates.js
packages/qiskit-sim/test/functional/gates.js

Add t gate as an alias for the r4 gate
This commit adds a gate named t as an alias for the phase shift PI/4
gate.

Add t gate as an alias for the r4 gate

---

CHANGELOG.md
packages/qiskit-sim/README.md

Add Gate as option to addGate API in README
This commit updates the addGate API documentation to include the Gate
instance as an alternative to passing in the gate name as a string.

Add Gate as option to addGate API in README

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/test/functional/Circuit.js

This commit introduces a print method to the Circuit class. The idea is
to give a visual representation of the quantum circuit.
The motivation for this is as a learning aid to help understand the
circuit created. The implementation can probably be made more efficient
but I wanted to get some feedback on this feature and if it is
worth pursuing/spending time on (or perhaps it could be useful as is
and developed further as required).
<details>
<summary>Node REPL example:</summary>
```console
> const { Circuit, Gate } = require('./index.js');
undefined
> const c = Circuit.createCircuit(1);
undefined
> c.addGate(Gate.x, 0, 0).print()
column 0
wire 0 ---[x]-----------
undefined
> c.addGate(Gate.cx, 1, [0, 1]).print()
column 0      column 1
wire 0 ---[x]-----------[cx]----------
|
wire 1 …
```

Add print circuit method

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js

Use spread operator in addGate
This commit uses the spread operator instead of looping over the wires
to populate the wireList.

Use spread operator in addGate

---

CHANGELOG.md
packages/qiskit-sim/README.md

Add print method to Circuit API documentation
I forgot to add this as part of https://github.com/Qiskit/qiskit-js/pull/59.

Add print method to Circuit API documentation

---

CHANGELOG.md
packages/qiskit-sim/README.md
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/test/functional/Circuit.js

This commit adds a method named add to the Circuit class which only
accepts Gate class instances as the type of the gate parameter.
The motivation for that when using a Gate class instance as the input to
the addGate method it reads a little verbose:
```js
circuit.addGate(Gate.h, 0, 0);
```
With this change adding this same gate would become:
```js
circuit.add(Gate.h, 0, 0);
```

Add 'add' method to Circuit class

---

packages/qiskit-qasm/README.md
packages/qiskit-qasm/example.qasm

This commit adds the missing fs and util modules from the parser example
in the README.
Currently just copying and pasting the example code in the README will fail due to the missing imports. This commit also adds a very simple `example.qasm` file to allow for quickly trying the sample code out.

Add missing require statements in parser example

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/test/functional/Circuit.js

Fix connection bug in printCircuit
This commit fixes a bug in printCircuit where connection between two
gates would be displayed before the start gate. For example, the
following could be printed which is incorrect:
```console
column 0      column 1
wire 0 -------------------------------
|
wire 1 ---[x]-----------[cx]----------
|
wire 2 -----------------[*]-----------
wire 3 -------------------------------
```

Fix connection bug in printCircuit

---

CHANGELOG.md
packages/qiskit-qasm/__snapshots__/parser.test.js
packages/qiskit-qasm/lib/grammar.jison

This commit updates the gate type in grammar to include a name and
instead set type to 'gate'.
The motivation for this is a follow up commit where the type can be used
to collect all the gates from a parsed QASM file and the assemble it
into a qiskit-sim Circuit.

Add name to the gate type in qasm parser

---

CHANGELOG.md
packages/qiskit-sim/lib/Circuit.js
packages/qiskit-sim/package.json
packages/qiskit-sim/test/functional/Circuit.js

This pull request adds a suggestion for a static function named fromQasm to the Circuit class which creates a Circuit from QASM source string or file.
This pull request contains two commit, one to qiskit-qasm and one to qiskit-sim. qiskit-sim depends on the update to qiskit-qasm and currently to test this, qiskit-qasm has to be linked:
```console
$ npm link ../qiskit-qasm/
```
Example usage:
```console
$ node -p <<'HERE'
const { Circuit, Gate } = require('./index.js');
const qasm = `
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
x q[0];
cx q[0],q[1];
measure q[0] -> c[0];
measure q[1] -> c[1];
`;
const c = Circuit.fromQasm(qasm);
c.print();
HERE
```
Output:
```console
column 0      column 1
wire 0 ---[x]-----------[cx]----------
|
wire 1 -----------------[*]-----------
```

 Add fromQasm/fromQasmFile functions to Circuit

---

CHANGELOG.md
packages/qiskit-qasm/lib/Parser.js
packages/qiskit-qasm/lib/QasmError.js
packages/qiskit-qasm/lib/grammar.jison
packages/qiskit-qasm/test/functional/parser.test.js
packages/qiskit-qasm/test/functional/qasmError.test.js

This contains two commits that make QasmError into a class and start using it for error handling when parsing using jison. 
For an example of usage see [parser.test.js](https://github.com/Qiskit/qiskit-js/compare/master...danbev:qasm-error?expand=1#diff-e00c52f8332212ba2d17b574145643d9). Currently only the line number is added to the error but more details can be added.

Use QasmError for qasm error handling

---

CHANGELOG.md
packages/qiskit-qasm/lib/Parser.js

Use TypeError as error for incorrect type
This is to make it consistent with other parts of the code base (at
least the parts I've seen that is) that use TypeError when an incorrect
type is passed to a function.

Use TypeError as error for incorrect type

---

CHANGELOG.md
packages/qiskit-qasm/lib/Parser.js

Make parser a member of class Parser
Currently parser is not a member of the Parser class and it looks like
the intention was to share it with all instances of class Parser. But it
also gets re-assigned in the constructor each time a new instance is
created. This commit makes parser a member instead, and perhaps a follow
up commit can take a look at sharing the parser (a quick test showed
that is was not as simple as I hoped).

Make parser a member of class Parser

---

CHANGELOG.md
packages/qiskit-sim/lib/gates.js
packages/qiskit-sim/test/functional/gates.js

This commit updates the Gate constructor to add the gate created to the
gates map if it does not exist.
The motivation for this was that when adding a custom gate it would not
be added to the gates map and hence an error would be thrown when trying
to execute the circuit.

add gate to gates map in constructor

---

CHANGELOG.md
packages/qiskit-sim/lib/gates.js
packages/qiskit-sim/test/functional/gates.js

This commit adds the ability to overwrite/redefine the a custom gate.
The motivation for this came from wanting to have multiple circuits in a
program and allow them to have the same name for a custom gate, but the
matrix for the gate would be different for each circuit.

allow custom gates to be overwritten

---

CHANGELOG.md
packages/qiskit-qasm/lib/grammar.jison

make registers const in grammar.jison
This commit makes the registers array const for consistency with the
other variables in the helpers section.

make registers const in grammar.jison

---

package-lock.json
package.json

add name to root package.json
This commit adds a name property to package.json in an attempt to fix
the build error that currently occurs when running the npm ci target.

add name to root package.json

---

CHANGELOG.md
packages/qiskit-qasm/lib/grammar.jison

fix indentation in grammer.jison
This commit makes the indentation of javascript in grammar.jison consistent.

fix indentation in grammer.jison

---

CHANGELOG.md
packages/qiskit/bin/cmds/parse.js

fix minor typo in parse.js
Just a correction of the warning message that is displayed.

fix minor typo in parse.js

---

CHANGELOG.md
packages/qiskit-qasm/package.json

add core director to files in package.json
Currently, the core directory is not included in the published npm
module which will lead to the following error:
```console
$ node index.js
QASM Version:  0.9.0
fs.js:126
throw err;
^
Error: ENOTDIR: not a directory, open
'qiskit-parser-issue/node_modules/@qiskit/qasm/core/qelib1.inc'
at Object.openSync (fs.js:447:3)
at Object.readFileSync (fs.js:349:35)
at new Parser
(/qiskit-parser-issue/node_modules/@qiskit/qasm/lib/Parser.js:34:25)
at Object.<anonymous> (/qiskit-parser-issue/index.js:18:16)
at Module._compile (internal/modules/cjs/loader.js:774:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
at Module.load (internal/modules/cjs/loader.js:641:32)
at Function.Module._load (internal/modules/cjs/loader.js:556:12)
at …
```

add core directory to files in package.json

---

CHANGELOG.md
examples/webpack/README.md
examples/webpack/package.json

remove init script from package.json
This commit removes the init script which was required for @qiskit/qasm
0.9.0 where `qelib.inc` was not included in the published modules. With
the next release this will be fixed and the example should work
standalone.
Fixes: https://github.com/Qiskit/qiskit-js/issues/86
@jesusprubio Could we do a release?

remove init script from package.json
